version: "2.2"
services:
  mqmstandby:
    image: mqm
    #restart: always
    volumes:
      - ./mqm:/mnt/mqm/
    environment:
      - LICENSE=accept 
      - MQ_QMGR_NAME=PMXSPEI01
    ports:
      - 1415:1414
      - 9444:9443
    networks:
    - mq
networks:
  mq:
    driver: bridge